name: 'Update CloudWatch RUM App Monitor SourceMaps URI'
description: 'Updates the SourceMaps S3 URI for the CloudWatch RUM app monitor after deployment.'
runs:
  using: 'composite'
  steps:
    - name: Update RUM App Monitor SourceMaps URI and Deobfuscation
      shell: bash
      run: |
        if [ -z "${{ inputs.rum_app_monitor_id }}" ]; then
          echo "❌ RUM app monitor name not provided!"
          exit 1
        fi
        if [ -z "${{ inputs.sourcemaps_bucket_name }}" ]; then
          echo "❌ Source maps bucket name not provided!"
          exit 1
        fi
        S3_URI="s3://${{ inputs.sourcemaps_bucket_name }}/"
        DEOBF_STATUS="${{ inputs.deobfuscation_status }}"
        DEOBF_S3_URI="${{ inputs.deobfuscation_s3_uri }}"
        DEOBF_CONFIG="{\"JavaScriptSourceMaps\":{\"Status\":\"$DEOBF_STATUS\",\"S3Uri\":\"$DEOBF_S3_URI\"}}"
        echo "🔄 Updating RUM app monitor '${{ inputs.rum_app_monitor_id }}' with SourceMaps S3 URI: $S3_URI and deobfuscation config: $DEOBF_CONFIG"
        aws rum update-app-monitor \
          --name "${{ inputs.rum_app_monitor_id }}" \
          --deobfuscation-configuration "$DEOBF_CONFIG"
inputs:
  rum_app_monitor_id:
    description: 'Name of the CloudWatch RUM app monitor.'
    required: true
  sourcemaps_bucket_name:
    description: 'Name of the S3 bucket containing source maps.'
    required: true
  deobfuscation_status:
    description: 'Enable or disable JS stack trace unminification (ENABLED or DISABLED).'
    required: false
    default: 'ENABLED'
  deobfuscation_s3_uri:
    description: 'S3 URI for source maps (required if status is ENABLED).'
    required: false
