name: 'Deploy to S3'
description: 'Sync built application files to S3 bucket with cache control'

inputs:
  s3_bucket:
    description: 'S3 bucket name'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
    default: 'eu-west-2'
  dist_dir:
    description: 'Distribution directory to deploy'
    required: true
    default: 'dist'

runs:
  using: 'composite'
  steps:
    - name: Deploy to S3
      shell: bash
      run: |
        S3_BUCKET="${{ inputs.s3_bucket }}"

        if [ -z "$S3_BUCKET" ]; then
          echo "Error: S3_BUCKET not provided."
          exit 1
        fi

        echo "Syncing to S3 bucket: $S3_BUCKET"

        # Sync all files except index.html with long cache
        aws s3 sync ${{ inputs.dist_dir }}/ s3://$S3_BUCKET \
          --delete \
          --region ${{ inputs.aws_region }} \
          --cache-control "public, max-age=31536000" \
          --exclude "index.html" \
          --exclude "*.map"

        # Upload index.html with no-cache
        aws s3 cp ${{ inputs.dist_dir }}/index.html s3://$S3_BUCKET/index.html \
          --region ${{ inputs.aws_region }} \
          --cache-control "no-cache, no-store, must-revalidate" \
          --metadata-directive REPLACE

        echo "Successfully deployed to S3!"
