name: 'Apply Terraform and Export Outputs'
description: 'Applies Terraform infrastructure changes and exports configuration outputs'

outputs:
  s3_bucket:
    description: 'S3 bucket name from Terraform outputs'
    value: ${{ steps.get-outputs.outputs.s3_bucket }}
  cloudfront_id:
    description: 'CloudFront distribution ID from Terraform outputs'
    value: ${{ steps.get-outputs.outputs.cloudfront_id }}
  cloudfront_domain:
    description: 'CloudFront domain name from Terraform outputs'
    value: ${{ steps.get-outputs.outputs.cloudfront_domain }}
  rum_app_monitor_id:
    description: 'CloudWatch RUM app monitor ID'
    value: ${{ steps.get-outputs.outputs.rum_app_monitor_id }}
  rum_identity_pool_id:
    description: 'Cognito identity pool ID for RUM'
    value: ${{ steps.get-outputs.outputs.rum_identity_pool_id }}
  rum_guest_role_arn:
    description: 'IAM role ARN for RUM guest access'
    value: ${{ steps.get-outputs.outputs.rum_guest_role_arn }}
  sourcemaps_bucket_name:
    description: 'S3 bucket for source maps'
    value: ${{ steps.get-outputs.outputs.sourcemaps_bucket_name }}

runs:
  using: 'composite'
  steps:
    - name: Initialize Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Apply infrastructure changes and export outputs
      id: get-outputs
      shell: bash
      run: |
        cd infra/terraform

        echo "ðŸ”§ Initializing Terraform..."
        terraform init

        echo "ï¿½ Planning Terraform changes..."
        terraform plan -out=tfplan

        echo "ðŸš€ Applying Terraform changes..."
        terraform apply -auto-approve tfplan

        echo "ï¿½ðŸ“Š Getting Terraform outputs..."

        # Get bucket, distribution ID, and CloudFront domain
        S3_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")
        CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
        CLOUDFRONT_DOMAIN=$(terraform output -raw cloudfront_domain_name 2>/dev/null || echo "")

        # Get CloudWatch RUM outputs
        RUM_APP_ID=$(terraform output -raw rum_app_monitor_id 2>/dev/null || echo "")
        RUM_IDENTITY_POOL=$(terraform output -raw rum_identity_pool_id 2>/dev/null || echo "")
        RUM_ROLE_ARN=$(terraform output -raw rum_guest_role_arn 2>/dev/null || echo "")
        SOURCEMAPS_BUCKET=$(terraform output -raw sourcemaps_bucket_name 2>/dev/null || echo "")

        # Output S3 bucket
        if [ -n "$S3_BUCKET" ]; then
          echo "âœ… Found S3 bucket: $S3_BUCKET"
          echo "s3_bucket=$S3_BUCKET" >> $GITHUB_OUTPUT
        else
          echo "âš ï¸  No S3 bucket found in Terraform outputs"
        fi

        # Output CloudFront distribution ID
        if [ -n "$CLOUDFRONT_ID" ]; then
          echo "âœ… Found CloudFront distribution: $CLOUDFRONT_ID"
          echo "cloudfront_id=$CLOUDFRONT_ID" >> $GITHUB_OUTPUT
        else
          echo "âš ï¸  No CloudFront distribution found in Terraform outputs"
        fi

        # Output CloudFront domain
        if [ -n "$CLOUDFRONT_DOMAIN" ]; then
          echo "âœ… Found CloudFront domain: $CLOUDFRONT_DOMAIN"
          echo "cloudfront_domain=$CLOUDFRONT_DOMAIN" >> $GITHUB_OUTPUT
        else
          echo "âš ï¸  No CloudFront domain found in Terraform outputs"
        fi

        # Output RUM configuration
        if [ -n "$RUM_APP_ID" ]; then
          echo "âœ… Found RUM app monitor: $RUM_APP_ID"
          echo "rum_app_monitor_id=$RUM_APP_ID" >> $GITHUB_OUTPUT
        else
          echo "âš ï¸  No RUM app monitor found (will be created on first apply)"
        fi

        if [ -n "$RUM_IDENTITY_POOL" ]; then
          echo "âœ… Found RUM identity pool: $RUM_IDENTITY_POOL"
          echo "rum_identity_pool_id=$RUM_IDENTITY_POOL" >> $GITHUB_OUTPUT
        fi

        if [ -n "$RUM_ROLE_ARN" ]; then
          echo "âœ… Found RUM role: $RUM_ROLE_ARN"
          echo "rum_guest_role_arn=$RUM_ROLE_ARN" >> $GITHUB_OUTPUT
        fi

        if [ -n "$SOURCEMAPS_BUCKET" ]; then
          echo "âœ… Found source maps bucket: $SOURCEMAPS_BUCKET"
          echo "sourcemaps_bucket_name=$SOURCEMAPS_BUCKET" >> $GITHUB_OUTPUT
        fi
